<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="6" total="19" passed="9" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-14T11:51:43 IST" name="Default suite" finished-at="2024-02-14T11:56:18 IST" duration-ms="274789">
    <groups>
    </groups>
    <test started-at="2024-02-14T11:51:43 IST" name="Default test" finished-at="2024-02-14T11:56:18 IST" duration-ms="274789">
      <class name="testcase.MyFirstTestFW">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:51:43 IST" name="setUp" finished-at="2024-02-14T11:51:50 IST" duration-ms="6920" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testSearchForLaptop()[pri:1, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:51:50 IST" name="testSearchForLaptop" finished-at="2024-02-14T11:51:58 IST" duration-ms="7180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSearchForLaptop -->
        <test-method signature="testSearchForBluetoothSpeaker()[pri:2, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:51:58 IST" name="testSearchForBluetoothSpeaker" finished-at="2024-02-14T11:52:11 IST" duration-ms="12916" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSearchForBluetoothSpeaker -->
        <test-method signature="testSearchWithoutProduct()[pri:3, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:52:11 IST" name="testSearchWithoutProduct" finished-at="2024-02-14T11:52:22 IST" duration-ms="11047" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSearchWithoutProduct -->
        <test-method signature="applyMultipleFiltersTest()[pri:4, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:52:22 IST" name="applyMultipleFiltersTest" finished-at="2024-02-14T11:53:17 IST" duration-ms="55586" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- applyMultipleFiltersTest -->
        <test-method signature="applyPriceFilterTest()[pri:5, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:53:17 IST" name="applyPriceFilterTest" finished-at="2024-02-14T11:53:40 IST" duration-ms="22921" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- applyPriceFilterTest -->
        <test-method signature="dynamicSearchResultsUpdateTest()[pri:6, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:53:40 IST" name="dynamicSearchResultsUpdateTest" finished-at="2024-02-14T11:54:06 IST" duration-ms="26147" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dynamicSearchResultsUpdateTest -->
        <test-method signature="verifyNoMatchingResultsMessage()[pri:7, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:54:06 IST" name="verifyNoMatchingResultsMessage" finished-at="2024-02-14T11:54:17 IST" duration-ms="11070" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Message indicating no matching results should be displayed. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Message indicating no matching results should be displayed. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at testcase.MyFirstTestFW.verifyNoMatchingResultsMessage(MyFirstTestFW.java:113)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNoMatchingResultsMessage -->
        <test-method signature="refineSearchWithFiltersTest()[pri:8, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:54:17 IST" name="refineSearchWithFiltersTest" finished-at="2024-02-14T11:54:44 IST" duration-ms="26779" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- refineSearchWithFiltersTest -->
        <test-method signature="resetSearchAndFiltersTest()[pri:9, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:54:44 IST" name="resetSearchAndFiltersTest" finished-at="2024-02-14T11:55:00 IST" duration-ms="16149" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetSearchAndFiltersTest -->
        <test-method signature="seamlessIntegrationTest()[pri:10, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:55:00 IST" name="seamlessIntegrationTest" finished-at="2024-02-14T11:55:20 IST" duration-ms="19397" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- seamlessIntegrationTest -->
        <test-method signature="verifyNumberOfResultsPerPage()[pri:11, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:55:20 IST" name="verifyNumberOfResultsPerPage" finished-at="2024-02-14T11:55:33 IST" duration-ms="13851" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Number of search results per page is not as expected expected [20] but found [-1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Number of search results per page is not as expected expected [20] but found [-1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at testcase.MyFirstTestFW.verifyNumberOfResultsPerPage(MyFirstTestFW.java:215)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNumberOfResultsPerPage -->
        <test-method signature="verifyNavigationToNextPage()[pri:12, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:55:33 IST" name="verifyNavigationToNextPage" finished-at="2024-02-14T11:55:57 IST" duration-ms="23236" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Navigation to the next page failed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Navigation to the next page failed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at testcase.MyFirstTestFW.verifyNavigationToNextPage(MyFirstTestFW.java:238)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNavigationToNextPage -->
        <test-method signature="verifyEmptySearchError()[pri:13, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:55:57 IST" name="verifyEmptySearchError" finished-at="2024-02-14T11:56:18 IST" duration-ms="20926" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error message for empty search query is not displayed. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error message for empty search query is not displayed. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at testcase.MyFirstTestFW.verifyEmptySearchError(MyFirstTestFW.java:253)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEmptySearchError -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcase.MyFirstTestFW@4135c3b]" started-at="2024-02-14T11:56:18 IST" name="tearDown" finished-at="2024-02-14T11:56:18 IST" duration-ms="593" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcase.MyFirstTestFW -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
